name: My First GitHub Action

on:
  push:  # Runs when code is pushed
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f1002633@ds.study.iitm.ac.in  # Step name contains your email
        run: echo "Hello, world!"
